"""S1.2: API 网关 Bearer Token 认证回归（白皮书 P1-2）。

- 无 Token → 401；错误 Token → 403；正确 Token → 200
- /ocos/health 等 UI/监控路径豁免
- OCOS_API_AUTH_DISABLED=true 显式关闭（仅开发环境）
- Token 自动生成并写回 config.json（OCOS_CONFIG_PATH 隔离到临时目录）
"""

from __future__ import annotations

import json
import os

import pytest
from fastapi.testclient import TestClient

from ocos.interaction.api import auth as api_auth
from ocos.interaction.api.server import app


@pytest.fixture
def env(tmp_path, monkeypatch):
    monkeypatch.setenv("OCOS_CONFIG_PATH", str(tmp_path / "config.json"))
    monkeypatch.setenv("OCOS_DB_PATH", str(tmp_path / "t.db"))
    monkeypatch.delenv("OCOS_API_TOKEN", raising=False)
    monkeypatch.delenv("OCOS_API_AUTH_DISABLED", raising=False)
    api_auth.reset_token_cache()
    yield monkeypatch
    api_auth.reset_token_cache()


@pytest.fixture
def client(env):
    return TestClient(app, raise_server_exceptions=False)


class TestApiAuth:
    def test_missing_token_401(self, client):
        resp = client.get("/ocos/outbox", params={"after": "0"})
        assert resp.status_code == 401

    def test_wrong_token_403(self, client, env):
        env.setenv("OCOS_API_TOKEN", "right-token")
        resp = client.get("/ocos/outbox", params={"after": "0"},
                          headers={"Authorization": "Bearer wrong-token"})
        assert resp.status_code == 403

    def test_correct_token_200(self, client, env):
        env.setenv("OCOS_API_TOKEN", "right-token")
        resp = client.get("/ocos/outbox", params={"after": "0"},
                          headers={"Authorization": "Bearer right-token"})
        assert resp.status_code == 200

    def test_health_and_ui_exempt(self, client):
        assert client.get("/ocos/health").status_code == 200
        assert client.get("/ocos/openapi.json").status_code == 200
        # UI 静态页依赖 fastapi responses；至少确认未走 401
        resp = client.get("/ui")
        assert resp.status_code != 401

    def test_auth_disabled_bypass(self, client, env):
        env.setenv("OCOS_API_AUTH_DISABLED", "true")
        resp = client.get("/ocos/outbox", params={"after": "0"})
        assert resp.status_code == 200

    def test_token_autogenerated_into_config(self, client, env):
        token = api_auth.get_api_token()
        assert token
        cfg_path = os.environ["OCOS_CONFIG_PATH"]
        cfg = json.loads(open(cfg_path, encoding="utf-8").read())
        assert cfg["api"]["token"] == token
        mode = os.stat(cfg_path).st_mode & 0o777
        assert mode == 0o600, f"config.json 权限应为 0600，实际 {oct(mode)}"
