"""interfaces — Agent 与各层接口适配器。

Protocol 定义，允许 MasterAgent 在运行时与各子系统解耦交互。
"""

from __future__ import annotations

from typing import Any, Optional, Protocol, runtime_checkable


@runtime_checkable
class IdentityAnchorProtocol(Protocol):
    """Agent 知道\"我是谁\"的接口。"""

    def get_identity_id(self) -> str: ...
    def get_name(self) -> str: ...
    def verify(self) -> bool: ...


@runtime_checkable
class GoalStackProtocol(Protocol):
    """Goal 栈的接口。"""

    def push(self, goal: Goal) -> None: ...
    def pop(self) -> Optional[Goal]: ...
    def peek(self) -> Optional[Goal]: ...
    def get_active(self) -> list[Goal]: ...
    def get_highest_priority(self) -> Optional[Goal]: ...


@runtime_checkable
class AttentionProtocol(Protocol):
    """注意力接口。"""

    def focus(self, item_id: str, item_type: str, priority: float) -> None: ...
    def unfocus(self, item_id: str) -> None: ...
    def current_focus(self) -> Optional[str]: ...
    @property
    def fatigue(self) -> float: ...
    def tick(self, seconds: float) -> None: ...


@runtime_checkable
class IntentProtocol(Protocol):
    """意图接口。"""

    def extract(self, text: str) -> dict[str, Any]: ...
    def get_intent_description(self) -> str: ...


@runtime_checkable
class WorkingMemoryProtocol(Protocol):
    """Agent 工作记忆接口。"""

    def add(self, item: Any) -> None: ...
    def remove(self, item_id: str) -> None: ...
    def clear(self) -> None: ...
    def current_focus(self) -> Optional[Any]: ...


@runtime_checkable
class CapabilityManagerProtocol(Protocol):
    """能力管理器接口。"""

    def has_capability(self, capability_id: str) -> bool: ...
    def list_capabilities(self) -> list[str]: ...
    def get_engine(self, engine_id: str) -> Any: ...


@runtime_checkable
class ExecutionManagerProtocol(Protocol):
    """执行管理器接口。"""

    def is_executing(self) -> bool: ...
    def get_current_action(self) -> Optional[dict[str, Any]]: ...
    def cancel(self) -> bool: ...
